/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ivan
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    DefaultTableModel model;

    public Registro() {
        initComponents();
        
        cargar(MainClass.agenda_electronica);
    }

    

    void limpiar() {
        txt_codigo.setText("");
        txt_nombre.setText("");
        txt_apellido.setText("");
        txt_direccion.setText("");
        txt_anotacion.setText("");

        txt_telefono.setText("");
        txt_telefono_casa.setText("");
        txt_telefono_movil.setText("");
        txt_telefono_trabajo.setText("");
        txt_email.setText("");

    }

   

    void cargar(ArrayList<Agenda> lista_agenda) {
        this.tb_agenda_electronica.removeAll();
        DefaultTableModel modelo = new DefaultTableModel();

        String[] Titulos = {"CÓDIGO", "NOMBRE", "APELLIDO", "DIRECIÓN", "ANOTACIÓN", "TELÉFONO", "TELÉFONO CASA", "TELÉFONO MÓVIL", "TELÉFONO TRABAJO", "EMAIL"};
        modelo.setColumnIdentifiers(Titulos);

        this.tb_agenda_electronica.setModel(modelo);

        String[] registros = new String[10];

        for (Agenda agenda : lista_agenda) {
            registros[0] = agenda.getCodigo();
            registros[1] = agenda.getNombre();
            registros[2] = agenda.getApellido();
            registros[3] = agenda.getDireccion();
            registros[4] = agenda.getAnotacion();
            registros[5] = agenda.getTelefono();
            registros[6] = agenda.getTelefono_casa();
            registros[7] = agenda.getTelefono_movil();
            registros[8] = agenda.getTelefono_trabajo();
            registros[9] = agenda.getEmail();

            modelo.addRow(registros);
        }

        model = modelo;
        tb_agenda_electronica.setModel(modelo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Label_NombreCliente = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        Label_ApellidoCliente = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();
        Label_NombreCliente2 = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        Label_ApellidoCliente1 = new javax.swing.JLabel();
        txt_direccion = new javax.swing.JTextField();
        txt_anotacion = new javax.swing.JTextField();
        Label_ApellidoCliente2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Label_ciCliente1 = new javax.swing.JLabel();
        lb_movil = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lb_tel_trabajo = new javax.swing.JLabel();
        Label_ciCliente4 = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        txt_telefono_casa = new javax.swing.JTextField();
        txt_telefono_movil = new javax.swing.JTextField();
        txt_telefono_trabajo = new javax.swing.JTextField();
        lb_emial = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();
        btnbuscar1 = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_agenda_electronica = new javax.swing.JTable();
        btn_eliminar = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(80, 80, 97));
        jLabel4.setText("Detalles de la persona");
        jLabel4.setToolTipText("");

        Label_NombreCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label_NombreCliente.setForeground(new java.awt.Color(102, 102, 102));
        Label_NombreCliente.setText("Nombre");
        Label_NombreCliente.setToolTipText("");

        Label_ApellidoCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label_ApellidoCliente.setForeground(new java.awt.Color(102, 102, 102));
        Label_ApellidoCliente.setText("Apellido");

        Label_NombreCliente2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label_NombreCliente2.setForeground(new java.awt.Color(102, 102, 102));
        Label_NombreCliente2.setText("Código ");
        Label_NombreCliente2.setToolTipText("");

        Label_ApellidoCliente1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label_ApellidoCliente1.setForeground(new java.awt.Color(102, 102, 102));
        Label_ApellidoCliente1.setText("Dirección ");

        Label_ApellidoCliente2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label_ApellidoCliente2.setForeground(new java.awt.Color(102, 102, 102));
        Label_ApellidoCliente2.setText("Anotaciones");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(Label_NombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nombre))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(Label_ApellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_apellido))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 278, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(Label_NombreCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_codigo))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(Label_ApellidoCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_direccion))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(Label_ApellidoCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_anotacion)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_NombreCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_NombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_ApellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_ApellidoCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_ApellidoCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_anotacion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        Label_ciCliente1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label_ciCliente1.setForeground(new java.awt.Color(102, 102, 102));
        Label_ciCliente1.setText("Teléfono casa");
        Label_ciCliente1.setToolTipText("");

        lb_movil.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_movil.setForeground(new java.awt.Color(102, 102, 102));
        lb_movil.setText("Teléfono móvil");
        lb_movil.setToolTipText("");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(80, 80, 97));
        jLabel11.setText("Detalles del contacto");
        jLabel11.setToolTipText("");

        lb_tel_trabajo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_tel_trabajo.setForeground(new java.awt.Color(102, 102, 102));
        lb_tel_trabajo.setText("Teléfono trabajo");

        Label_ciCliente4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label_ciCliente4.setForeground(new java.awt.Color(102, 102, 102));
        Label_ciCliente4.setText("Teléfono");
        Label_ciCliente4.setToolTipText("");

        lb_emial.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_emial.setForeground(new java.awt.Color(102, 102, 102));
        lb_emial.setText("Email");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lb_emial, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_email, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
                    .addComponent(jLabel11)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_movil, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_tel_trabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_ciCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_ciCliente4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_telefono_casa)
                            .addComponent(txt_telefono_movil)
                            .addComponent(txt_telefono_trabajo, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(txt_telefono))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_ciCliente4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_ciCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_telefono_casa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_movil, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_telefono_movil, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_tel_trabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_telefono_trabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_emial, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setText("BUSCAR:");

        btnbuscar1.setText("Buscar");
        btnbuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscar1ActionPerformed(evt);
            }
        });

        btnbuscar.setText("Mostrar Todos");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        tb_agenda_electronica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tb_agenda_electronica);

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnactualizar.setText("Actualizar");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_limpiar.setText("Limpiar");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnbuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnbuscar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar)
                    .addComponent(jLabel10)
                    .addComponent(btnbuscar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscar1ActionPerformed
        //declaramos un variable que contendra el codigo a buscar
        String codigo = txt_buscar.getText();
        //declaramos un array list de tipo agenda 
        ArrayList<Agenda> nueva_agenda = new ArrayList<Agenda>();
        //creamos un nuevo objeto agenda
        Agenda agenda = new Agenda();
        //accedemos al metodo buscarDatos de la clase Agenda y le pasosmo por parametro la lista principal del main y el codigo a buscar
        //eset metodo retornara una lista de datos encontrados
        nueva_agenda = agenda.BuscarDatos(MainClass.agenda_electronica, codigo);
        //acutuaizamos la tabla con la fucnion cargar y le pasamo por parametro la nueva lista encontrada
        cargar(nueva_agenda);
    }//GEN-LAST:event_btnbuscar1ActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed

        //buscamos todos los registros de la lista principal del main principal
        cargar(MainClass.agenda_electronica);
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
       
        //buscamos una fila que este seleccionada
        int fila = tb_agenda_electronica.getSelectedRow();

        //declaramos una variable que contendra el codigo de la fila seleccionada
        String codigo = "";
       //extraemos el codigo de la fila sleccionada
        codigo = tb_agenda_electronica.getValueAt(fila, 0).toString();
        
        //comparamos si hay una fila selecioanda
        if (fila >= 0) {
            //creamo una nueava agenda con el constructro vacio
            Agenda agenda = new Agenda();
            //aacedemos al metodo eliminarDatos y le pasamos por parametro la lista de agenda electroica y el codigo del registro que vamos a eliminar
            agenda.eliminarDatos(MainClass.agenda_electronica, codigo);
            
            //actualizamos la tabla con la funcion cargar
            cargar(MainClass.agenda_electronica);
           
        } else {
            JOptionPane.showMessageDialog(this, "No ha selecionada ninguna fila");
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
//declaramos las variable para obtener los valores de las cajas de texto
        String codigo, nombre, apellido, direccion, anotacion, telefono, telefono_casa, telefono_movil, telefono_trabajo, email;

        codigo = txt_codigo.getText();
        nombre = txt_nombre.getText();
        apellido = txt_apellido.getText();
        direccion = txt_direccion.getText();
        anotacion = txt_anotacion.getText();

        telefono = txt_telefono.getText();
        telefono_casa = txt_telefono_casa.getText();
        telefono_movil = txt_telefono_movil.getText();
        telefono_trabajo = txt_telefono_trabajo.getText();
        email = txt_email.getText();
        //creamos un nuevo objeto agenda con los valore obteniddos
        Agenda agenda = new Agenda(codigo, nombre, apellido, direccion, anotacion, telefono, telefono_casa, telefono_movil, telefono_trabajo, email);
        //guardamos el nuevo objeto agenda creado 
        agenda.insertarDatos(MainClass.agenda_electronica, agenda);
        
        //imprimismos un mensaje 
        JOptionPane.showMessageDialog(null, "Guardado exitosamente");
        //limpiamos los campos con la funcion limpiar
        limpiar();
        
        //actualizamos la tabla con la funcion cargar
        cargar(MainClass.agenda_electronica);
       
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed

        //declaramos las variable para obtener los valores de las cajas de texto
        String codigo, nombre, apellido, direccion, anotacion, telefono, telefono_casa, telefono_movil, telefono_trabajo, email;

        codigo = txt_codigo.getText();
        nombre = txt_nombre.getText();
        apellido = txt_apellido.getText();
        direccion = txt_direccion.getText();
        anotacion = txt_anotacion.getText();

        telefono = txt_telefono.getText();
        telefono_casa = txt_telefono_casa.getText();
        telefono_movil = txt_telefono_movil.getText();
        telefono_trabajo = txt_telefono_trabajo.getText();
        email = txt_email.getText();

        //creamos un nuevo objeto agenda con los valore obteniddos
        Agenda agenda = new Agenda(codigo, nombre, apellido, direccion, anotacion, telefono, telefono_casa, telefono_movil, telefono_trabajo, email);

        //actualizamos  el  objeto agenda creado 
        agenda.actualizarDatos(MainClass.agenda_electronica, agenda, codigo);
        
        //llamos a la funcion para cargar los nuevos registros
        cargar(MainClass.agenda_electronica);
        
        //llamos a la funcion de limpiar datos
        limpiar();
        
        
        //final mente desbloqueamos el campo de textodel codigo
        txt_codigo.setEnabled(true);

    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        //bloqueamos el campo del codigo para editar
        txt_codigo.setEnabled(false);
        
        //ontenemos la fila selccionada
        int filamodificar = tb_agenda_electronica.getSelectedRow();
        
        //comparamos si hay una fila seleccionada
        if (filamodificar >= 0) {

            txt_codigo.setText(tb_agenda_electronica.getValueAt(filamodificar, 0).toString());
            txt_nombre.setText(tb_agenda_electronica.getValueAt(filamodificar, 1).toString());
            txt_apellido.setText(tb_agenda_electronica.getValueAt(filamodificar, 2).toString());
            txt_direccion.setText(tb_agenda_electronica.getValueAt(filamodificar, 3).toString());
            txt_anotacion.setText(tb_agenda_electronica.getValueAt(filamodificar, 4).toString());

            txt_telefono.setText(tb_agenda_electronica.getValueAt(filamodificar, 5).toString());
            txt_telefono_casa.setText(tb_agenda_electronica.getValueAt(filamodificar, 6).toString());
            txt_telefono_movil.setText(tb_agenda_electronica.getValueAt(filamodificar, 7).toString());
            txt_telefono_trabajo.setText(tb_agenda_electronica.getValueAt(filamodificar, 8).toString());
            txt_email.setText(tb_agenda_electronica.getValueAt(filamodificar, 9).toString());

        } else {
            JOptionPane.showMessageDialog(this, "No ha seleccionado ");
        }

    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btn_limpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_ApellidoCliente;
    private javax.swing.JLabel Label_ApellidoCliente1;
    private javax.swing.JLabel Label_ApellidoCliente2;
    private javax.swing.JLabel Label_NombreCliente;
    private javax.swing.JLabel Label_NombreCliente2;
    private javax.swing.JLabel Label_ciCliente1;
    private javax.swing.JLabel Label_ciCliente4;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btnbuscar1;
    private javax.swing.JButton btnguardar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_emial;
    private javax.swing.JLabel lb_movil;
    private javax.swing.JLabel lb_tel_trabajo;
    private javax.swing.JTable tb_agenda_electronica;
    private javax.swing.JTextField txt_anotacion;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    private javax.swing.JTextField txt_telefono_casa;
    private javax.swing.JTextField txt_telefono_movil;
    private javax.swing.JTextField txt_telefono_trabajo;
    // End of variables declaration//GEN-END:variables
}
